### ISSUE TITLE
Unloading the cog doesn't revert [p]help

### ISSUE THREAD

**Issue by Chovin** [Nerdietony/Nerdie-Cogs#3]
https://github.com/Cog-Creators/Cog-Board/issues/8

Pleas see [26-Cogs/trigger](https://github.com/Twentysix26/26-Cogs/blob/master/trigger/trigger.py) for an example on how to do this

**Comment by Nerdietony** [comment]
True but once i unload the cog how do i enabled the old help command.

**Comment by Nerdietony** [comment]
@Chovin

**Comment by Nerdietony** [comment]
Lock. IF you want to reable it then unload the cog and restart the bot.

**Comment by Chovin** [comment]
see [Dumb-Cogs/lolz](https://github.com/irdumbs/Dumb-Cogs/tree/master/lolz) for a not the best, but working, example.

**Comment by Nerdietony** [comment]
I'll look into it...
