### ISSUE TITLE
Status doesn't update automatically

### ISSUE THREAD

**Issue by FloatCobra** [Nerdietony/Nerdie-Cogs#4]
Toggling botstats on with a timeout of 15 seconds sets the status, then doesn't update until you disable and re-enable botstats

Logs showed something similar to "change_status is deprecated, use change_presence instead"

**Comment by Nerdietony** [comment]
Do u have the latest version? The problem was fixed awhile back

**Comment by FloatCobra** [comment]
the latest version on this repo uses change_status :T

**Comment by FloatCobra** [comment]
Also even after unloading the cog, it keeps setting it

**Comment by FloatCobra** [comment]
http://i.imgur.com/2mBaqTF.png
http://i.imgur.com/uaHKY2F.png

**Comment by Nerdietony** [comment]
I'm referring to the updated part

**Comment by FloatCobra** [comment]
I am on the latest update, yes

**Comment by Nerdietony** [comment]
Are u sure? It updates fine for me

**Comment by Nerdietony** [comment]
Should work fine now. Reopen the issue if you have any more problems...
