### ISSUE TITLE
Error in command 'help' - NameError: name 'wow' is not defined

### ISSUE THREAD

**Issue by DesignsForCharity** [Nerdietony/Nerdie-Cogs#5]
I loaded customhelp cog (From Nerdie-Cogs by Nerdietony beta), And I setted up the cog properly, but when I say `[p]help` ([p] = !) the bot replys `Error in command 'help' - NameError: name 'wow' is not defined`

![](https://cdn.discordapp.com/attachments/270099060063469569/289316557044056064/unknown.png)

**Comment by Nerdietony** [comment]
Fixed.
